### ISSUE TITLE
Critical bug: GPS crashes if the Window 7 user folder name contains non-English symbols

### ISSUE THREAD

**Issue by financial-engineer** [AdaCore/gps#5]
Dear GPS developers!
I downloaded GNAT GPL 2016 from your official website: http://libre.adacore.com/download and installed it on the Russian release of Windows 7. 
The GPS crashes immediately after its launch while trying to create the .gps sub-folder in the following folder: c:\Users\\_UserName_. In non-English releases of Windows users can create user accounts (and Windows 7 creates the corresponding folder c:\Users\\_UserName_) containing **non-English** symbols, for example, Офис (that is "Office" in English). I think the same situation could arise while launching the GPS on the Arabic, Chinese and other non-English releases of the Windows operating system. 
Please fix this critical bug! I believe that the GPS for Windows should recognize and work well with folder names and filenames containing non-English symbols.

**Comment by setton** [comment]
Hello! We'll have a look.

**Comment by setton** [comment]
By the way, perhaps you can work around this issue by setting the environment variable GPS_HOME to point to C:\temp, for instance.

**Comment by financial-engineer** [comment]
OK, thank you for your advice. 
But please fix the bug I mentioned. This bug leaves a painful impression of the quality of software testing and causes damage to your company's reputation among your would-be end users who work on non-English releases of the Windows OS. I think your software product have to be a synonym of the highest quality, globalization readiness and reliability in everything.

**Comment by financial-engineer** [comment]
@setton 
Nicolas, I think there is no need to buy and install the Russian release of Windows 7 for testing this bug. 
The bug will arise if you create a new user account on your _English_ version of Windows with its name that contains _non-English_ symbols (you can just copy-and-paste its would-be name in Russian: "Офис"), log in as that new user, install GNAT GPL 2016 for that user and try to run GPS.

**Comment by setton** [comment]
We agree and definitely want to fix this. (We're quite surprised actually that this issue has never arisen before).

**Comment by AnthonyLeonardoGracio** [comment]
Hello, 

This issue is a bit more complex than it seems: it's actually related to some DBUS limitations with non-english characters.

We have an internal ticket for this, and will let you know once it's fixed.

Regards,

**Comment by ogorodnik** [comment]
Hello,
This issue has been fixed in development version of GPS. The fix will be available in the next major version of GPS.

**Comment by Entomy** [comment]
<img width="689" alt="Annotation 2019-11-19 084716" src="https://user-images.githubusercontent.com/25399505/69151925-998b1080-0aa9-11ea-8096-85e64489c05c.png">

Seems like something very similar is still happening. While not crashing with error messages, it just doesn't run and doesn't create the .gps folder.

And there's definately nothing wrong with the install, as I it created the .gps folder just fine on my own account.

![image](https://user-images.githubusercontent.com/25399505/69152101-dce57f00-0aa9-11ea-9a35-90d8516fa79e.png)

And has no problem launching on my account.

![image](https://user-images.githubusercontent.com/25399505/69152131-e66ee700-0aa9-11ea-871a-b6380f186c28.png)

**Comment by ogorodnik** [comment]
Which version of GPS do you use?

**Comment by Entomy** [comment]
I tested this against GPS 19.1 (20190106) hosted on x86_64-pc-mingw32, GNAT Community 2019 (20190517-83)

**Comment by ogorodnik** [comment]
Thank you for the information. We'll test this on our side and let you know.

**Comment by ogorodnik** [comment]
GPS from community-2019 does not contain the fix.
The patch was submitted on 2019-03-28 but GPS was prepared for release on 2019-01-06. So the fix will be available in the community 2020 release.

Best regards,
Andry.
