### ISSUE TITLE
GPS and GPR don't match up when adding a new file

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#61]
When creating a new file within GPS's dialogs, the file name entered into the GPR doesn't match the file name entered into GPS. Alternatively, GPS doesn't create proper file names. Seems like the former though.

Steps to reproduce:
Create New Project -> Simple Ada Project
New -> Ada Main Unit
Name new unit "main.adb" through the dialog prompt

GPR will now read `for Main use ("main.adb", "main.adb");` while GPS actually created a file named `main-adb.adb`.

**Comment by ogorodnik** [comment]
Hello Entomy,
We will fix this.
Thank you for the report.

**Comment by AnthonyLeonardoGracio** [comment]
This is now fixed in the GPS development version: the entry will be highlighted in red when a filename instead of a unit name and the OK button becomes unclickable.

Regards,

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/58480341-2de26f00-8128-11e9-9409-f1f7e7009061.png)

@AnthonyLeonardoGracio No it doesn't, this is on the new 20190106 build.

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/58480457-63875800-8128-11e9-8b42-2ce85ded1c0b.png)

![image](https://user-images.githubusercontent.com/25399505/58480490-76019180-8128-11e9-897a-0855e251fed6.png)

@AnthonyLeonardoGracio And this wasn't fixed at all

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

It's not fixed in the Community version since it has been built in January. The fix will only be available next year's Community version unfortunately.

PS: you don't need to be rude, we are doing our best

**Comment by Entomy** [comment]
I made no criticisms on any person. I made no criticisms of any product. I just said it was still failing on a certain build. If that's being rude, then filing bug reports are rude.
